language: python
python:
  - "3.2"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install gcc-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - gcc --version
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt
  - make all

script: true

notifications:
  irc:
    channels: "irc.psas.pdx.edu#psas"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
    use_notice: true
  email: false
